# Change these first
owner: jckylalaina # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SKIILLZ
    url: $SKIILLZ
  - name: Eufonie
    url: $EUFONIE
  - name: Odoo Eufonie
    url: $ODOO
  - name: Moodle
    url: $MOODLE
    method: GET
  - name: Click
    url: $CLICK
  - name: Guide Maurice
    url: $GUIDE_M
  - name: Maurice
    url: $MAURICE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime by jacky"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
